### ISSUE TITLE
Unable to access opensearch-dashboards using domain name

### ISSUE THREAD

**Issue by shubhikaushal7290** [opensearch-project/helm-charts#354] opened 2022-12-07 10:51 UTC
I have setup of opensearch-dashboards, I'm able to view applications logs in opensearch-dashboards while access dashboard using http://IP:PORT/

However,  when I add context path/basepath details in values.yaml file of opensearch-dashboard helm charts, then it starts throwing error in opensearch-dashboards pod  logs, like mentioned below:

pod logs:

 {"type":"log","@timestamp":"2022-12-07T07:09:58Z","tags":["error","opensearch","data"],"pid":1,"message":"[ResponseError]: Response Error"}

values.yaml file detail:

config:
   opensearch_dashboards.yml: |
      server:
          name: dashboards
          host: "0.0.0.0"
          basePath: "/opensearch-dashboards"
          rewriteBasePath: true 

<img width="770" alt="domain_name_opensearch_dashboard" src="https://user-images.githubusercontent.com/89378956/206146771-5ba6f919-763d-4778-9d30-947099e810f5.PNG">

<img width="942" alt="opensearch-dashboard logs" src="https://user-images.githubusercontent.com/89378956/206146782-3b2c58c8-ef38-46c8-ab20-af2181071337.PNG">

<img width="343" alt="opensearch-dashboard-config" src="https://user-images.githubusercontent.com/89378956/206146790-1e92a970-9d74-4f74-a3c4-e2275048d5a3.PNG">

******  Please help me on this and let me know if require more information.

**Comment by bbarani** [comment] 2023-01-11 21:55
Closing this issue as duplicate of https://github.com/opensearch-project/helm-charts/issues/365

**Closed by bbarani** 2023-01-11 21:55 UTC
