### ISSUE TITLE
[Enhancement][opensearch-dashboards] Add k8s readiness probe

### ISSUE THREAD

**Issue by Sebor** [opensearch-project/helm-charts#112] opened 2021-10-29 16:24 UTC
**Is your feature request related to a problem? Please describe.**
At the present time there are no any probes in this chart.  However, for example, this [section](https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/values.yaml#L306) in `values.yaml` is presented

**Describe the solution you'd like**
it would be nice to have a readiness probe in the chart

**Comment by sastorsl** [comment] 2021-11-02 18:59
Duplicate of #44 ?

**Comment by Sebor** [comment] 2021-11-03 14:32
> Duplicate of #44 ?

You are right. But the title of the old issue looks a bit strange imho.
So I've renamed this issue to be more specific

**Comment by faabsen** [comment] 2023-02-09 14:14
Follow up: hasn't this been already fixed with #329 and #333 and is a duplicate of #117?

**Comment by TheAlgo** [comment] 2023-02-10 17:06
Yes I think we can close this. Thanks @faabsen 

@Sebor Feel free to re-open if you have further questions.

**Closed by TheAlgo** 2023-02-10 17:06 UTC
Labels: enhancement
