### ISSUE TITLE
forbidden sysctl: "vm.max_map_count" not whitelisted

### ISSUE THREAD

**Issue by dyipon** [opensearch-project/helm-charts#87] opened 2021-10-07 17:37 UTC
Hi,

i've tried to install opensearch via helm, but pods are pending with this message:
forbidden sysctl: "vm.max_map_count" not whitelisted

I've tried to override the security settings, but did not help:
```console
helm upgrade --install opensearch opensearch/opensearch --set sysctl.enabled=true --set podSecurityContext.runAsUser=0 --set securityContext.runAsNonRoot=false >test.yml
```

Im try to migrate from ES, but theirs helm using a bit different method:
they are using a fully privileges initcontainer to set the vm.max_map_count:
```
   initContainers:
154       - name: configure-sysctl
155         securityContext:
156           runAsUser: 0
157           privileged: true
158         image: "docker.elastic.co/elasticsearch/elasticsearch:7.14.0"
159         imagePullPolicy: "IfNotPresent"
160         command: ["sysctl", "-w", "vm.max_map_count=262144"]
161         resources:
```

What would be the best practice? Others does not have this situation?

thanks

**Comment by sdwerwed** [comment] 2021-10-08 21:31
Maybe try this init container as a workaround

```
# # Enable on the first time
# sysctl:
#   enabled: false


extraInitContainers:
  ## Image that performs the sysctl operation to modify Kernel settings (needed sometimes to avoid boot errors)
  - name: sysctl
    image: docker.io/bitnami/bitnami-shell:10-debian-10-r199
    imagePullPolicy: "IfNotPresent"
    command:
      - /bin/bash
      - -ec
      - |
        CURRENT=`sysctl -n vm.max_map_count`;
        DESIRED="262144";
        echo "$CURRENT $DESIRED"
        if [ "$DESIRED" -gt "$CURRENT" ]; then
            sysctl -w vm.max_map_count=262144;
        fi;
        echo "$CURRENT $DESIRED"
        CURRENT=`sysctl -n fs.file-max`;
        DESIRED="65536";
        echo "$CURRENT $DESIRED"
        if [ "$DESIRED" -gt "$CURRENT" ]; then
            sysctl -w fs.file-max=65536;
        fi;
        echo "$CURRENT $DESIRED"
    securityContext:
      privileged: true
      
```

**Comment by DandyDeveloper** [comment] 2021-10-13 01:03
@dyipon @sdwerwed By default;

https://github.com/opensearch-project/helm-charts/blob/8aaa89e2ed43896910dd50a57a50e05380ddea71/charts/opensearch/values.yaml#L373

This enabled will result in this being enabled on the sts;

```sh
        {{- if .Values.sysctl.enabled }}
        sysctls:
        - name: vm.max_map_count
          value: {{ .Values.sysctlVmMaxMapCount | quote }}
        {{- end }}
```

As explained in those values, your kubelet / node needs to be allowed to access these things (Per the comments): 
https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html)
https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/

It's not a bug, as the container points out, Kubernetes/CRI can't access the system option because it isn't whitelisted. 

The recommendation of enabling `privileged: true` is not good and dangerous.

**Comment by dyipon** [comment] 2021-10-13 07:31
@DandyDeveloper  ES Helm chart using 
https://github.com/elastic/helm-charts/blob/e077086c74d3b9e121cec1d93f04d8418599bae4/elasticsearch/templates/statefulset.yaml#L166 
``` privileged: true ```

**Comment by DandyDeveloper** [comment] 2021-10-13 07:33
@dyipon That doesn't make it safe ;)

**Comment by acjohnson** [comment] 2021-10-18 19:00
Sadly on GKE adding `vm.max_map_count` to the kublet `--allowed-unsafe-sysctls` arg is not a supported option as `vm.max_map_count` is an "unsupported" kernel parameter...

This is the error you'll get if you try to set it using `gcloud beta container node-pools create`
```shell
ERROR: (gcloud.beta.container.node-pools.create) ResponseError: code=400, message=Unsupported kernel parameter vm.max_map_count.
```
So it looks like the privileged sysctl init container is the only decent option currently for opensearch...

**Comment by DandyDeveloper** [comment] 2021-11-30 01:09
Unfortunately, regarding GKE, there's just not many other options. I don't like the idea of `privileged: true` on a initContainer, but it does seem to be the only option here. 

Per the above comment though, there definitely needs to be some understanding that either;

* Nodes have to be prepared beforehand with the `vm.max_map_count` specifically for OpenSearch
* Kubelet needs to have explicitly access to the necessary sysctls (even if it is considered unsafe)

Otherwise, the best bet is `privileged: true` which isn't good advice but we don't really have many other options.

**Comment by smlx** [comment] 2021-12-01 02:10
At least scoping it to an init container is a reasonable compromise for now - as long as we can enable the init container via a flag.

**Comment by peterzhuamazon** [comment] 2022-02-20 17:16
Close this for now as it seems to be resolved by community.
Please feel free to re-open if you still have questions.

Thanks.

**Closed by peterzhuamazon** 2022-02-20 17:16 UTC

**Comment by acjohnson** [comment] 2022-02-20 18:48
It would be nice if the init container method in this issue could become an official part of this helm chart and could be toggled with a bool value.

**Comment by peterzhuamazon** [comment] 2022-02-20 19:15
> It would be nice if the init container method in this issue could become an official part of this helm chart and could be toggled with a bool value.

Hi @acjohnson feel free to contribute the changes if you are available for that :)
We welcome community contributions to help improve helm charts every day.

Thanks.

**Comment by DandyDeveloper** [comment] 2022-02-24 03:18
I'm indifferent about adding it. If there is an overwhelming (somewhat) need for it. It should be done. Community driver after all

**Comment by nitinjagjivan** [comment] 2022-11-16 13:46
With k8s v1.25 PodSecurity "baseline:latest" or PodSecurity "restricted:latest",  initContainer solution provided above doesn't work as it needs **securityContext.privileged: true** which is dangerous as well.

Also [helm-charts/charts/opensearch/values.yaml](https://github.com/opensearch-project/helm-charts/blob/8aaa89e2ed43896910dd50a57a50e05380ddea71/charts/opensearch/values.yaml#L373) doesn't work as it does the same thing.

error:
would violate PodSecurity "baseline:latest": forbidden sysctls (vm.max_map_count)

**Comment by AriBerisha** [comment] 2023-11-24 11:01
> Maybe try this init container as a workaround
> 
> ```
> # # Enable on the first time
> # sysctl:
> #   enabled: false
> 
> 
> extraInitContainers:
>   ## Image that performs the sysctl operation to modify Kernel settings (needed sometimes to avoid boot errors)
>   - name: sysctl
>     image: docker.io/bitnami/bitnami-shell:10-debian-10-r199
>     imagePullPolicy: "IfNotPresent"
>     command:
>       - /bin/bash
>       - -ec
>       - |
>         CURRENT=`sysctl -n vm.max_map_count`;
>         DESIRED="262144";
>         if [ "$DESIRED" -gt "$CURRENT" ]; then
>             sysctl -w vm.max_map_count=262144;
>         fi;
>         CURRENT=`sysctl -n fs.file-max`;
>         DESIRED="65536";
>         if [ "$DESIRED" -gt "$CURRENT" ]; then
>             sysctl -w fs.file-max=65536;
>         fi;
>     securityContext:
>       #runAsUser: 0
>       privileged: true
>       
> ```

I would like to thank you, this works very well for deprecated kubernetes version 1.15 and official helm chart of opensearch version 2.11.0
